window.movies = [
  // Popular Movies (1-15)
  { id: 1, title: "Dune: Part Two", image: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg", progress: 30, category: "popular" },
  { id: 2, title: "Furiosa: A Mad Max Saga", image: "https://image.tmdb.org/t/p/w500/iADOJ8ZymD2LvDSmody4O4Slj0y.jpg", progress: 0, category: "popular" },
  { id: 3, title: "The Fall Guy", image: "https://image.tmdb.org/t/p/w500/tSz1qsmSJon0rqjHBxXZmrotD35.jpg", progress: 75, category: "popular" },
  { id: 4, title: "Kingdom of the Planet of the Apes", image: "https://image.tmdb.org/t/p/w500/wsRFOm6VzGbaFWQ5X2mYRgvYSmZ.jpg", progress: 20, category: "popular" },
  { id: 5, title: "Godzilla x Kong: The New Empire", image: "https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg", progress: 10, category: "popular" },
  { id: 6, title: "Challengers", image: "https://image.tmdb.org/t/p/w500/8ZTVqvKDQ8emSGUEMjsS4yRQwr9.jpg", progress: 50, category: "popular" },
  { id: 7, title: "Kung Fu Panda 4", image: "https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg", progress: 0, category: "popular" },
  { id: 8, title: "Ghostbusters: Frozen Empire", image: "https://image.tmdb.org/t/p/w500/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg", progress: 90, category: "popular" },
  { id: 9, title: "Civil War", image: "https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg", progress: 50, category: "popular" },
  { id: 10, title: "Abigail", image: "https://image.tmdb.org/t/p/w500/7qxG0zyt29BI0IzFDfsps62kbQi.jpg", progress: 70, category: "popular" },
  { id: 11, title: "The Ministry of Ungentlemanly Warfare", image: "https://image.tmdb.org/t/p/w500/1QX2OHB6T0Z8N1MC8WfC9Kk0QSy.jpg", progress: 25, category: "popular" },
  { id: 12, title: "IF", image: "https://image.tmdb.org/t/p/w500/xKQ7ZP0X7fgxpyVYyiPZ2iUNc4S.jpg", progress: 15, category: "popular" },
  { id: 13, title: "The First Omen", image: "https://image.tmdb.org/t/p/w500/w6e0XZreiyW4mGlLRHEG8ipff7b.jpg", progress: 60, category: "popular" },
  { id: 14, title: "Deadpool & Wolverine", image: "https://image.tmdb.org/t/p/w500/fXH3uGn0jRuD8G0qQHk81F4VrNo.jpg", progress: 0, category: "popular" },
  { id: 15, title: "A Quiet Place: Day One", image: "https://image.tmdb.org/t/p/w500/2mQ5Q5mZvYJ2eHaOofYxTZ5u84T.jpg", progress: 0, category: "popular" },

  // Trending (16-30)
  { id: 16, title: "Inside Out 2", image: "https://image.tmdb.org/t/p/w500/4TpQ5ow5M8Q5cVug8RGnKJvBFGz.jpg", progress: 0, category: "trending" },
  { id: 17, title: "The Garfield Movie", image: "https://image.tmdb.org/t/p/w500/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg", progress: 40, category: "trending" },
  { id: 18, title: "Bad Boys: Ride or Die", image: "https://image.tmdb.org/t/p/w500/y5k3E7wzXQ5QvAIIq1ZQZR6T6k9.jpg", progress: 0, category: "trending" },
  { id: 19, title: "The Strangers: Chapter 1", image: "https://image.tmdb.org/t/p/w500/2ZqWogBj2Ho3kKZ7ETM9YjJf8Z5.jpg", progress: 30, category: "trending" },
  { id: 20, title: "The Beekeeper", image: "https://image.tmdb.org/t/p/w500/A7EByudX0eOzlkQ2FIbogzyazm2.jpg", progress: 80, category: "trending" },
  { id: 21, title: "Argylle", image: "https://image.tmdb.org/t/p/w500/95VlSEfLMqeX36UVcHJuNlWEpwf.jpg", progress: 10, category: "trending" },
  { id: 22, title: "The Marvels", image: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg", progress: 45, category: "trending" },
  { id: 23, title: "Wonka", image: "https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg", progress: 65, category: "trending" },
  { id: 24, title: "Migration", image: "https://image.tmdb.org/t/p/w500/2fEZT4zXhV5R7Q4TjF0QaYJjYJp.jpg", progress: 25, category: "trending" },
  { id: 25, title: "Anyone But You", image: "https://image.tmdb.org/t/p/w500/5qHoazZiaLe7oFBok7XlUhg96fZ.jpg", progress: 0, category: "trending" },
  { id: 26, title: "Poor Things", image: "https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg", progress: 90, category: "trending" },
  { id: 27, title: "The Hunger Games: The Ballad of Songbirds & Snakes", image: "https://image.tmdb.org/t/p/w500/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg", progress: 50, category: "trending" },
  { id: 28, title: "Napoleon", image: "https://image.tmdb.org/t/p/w500/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg", progress: 30, category: "trending" },
  { id: 29, title: "Wish", image: "https://image.tmdb.org/t/p/w500/8QtDqZQNNrzUTAyMkXdz1SW3m1U.jpg", progress: 10, category: "trending" },
  { id: 30, title: "Aquaman and the Lost Kingdom", image: "https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg", progress: 60, category: "trending" },

  // Genres (31-40)
  { id: 31, title: "Oppenheimer", image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", progress: 100, category: "genres" },
  { id: 32, title: "Barbie", image: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", progress: 100, category: "genres" },
  { id: 33, title: "The Super Mario Bros. Movie", image: "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg", progress: 75, category: "genres" },
  { id: 34, title: "John Wick: Chapter 4", image: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg", progress: 50, category: "genres" },
  { id: 35, title: "Mission: Impossible - Dead Reckoning Part One", image: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg", progress: 40, category: "genres" },
  { id: 36, title: "Transformers: Rise of the Beasts", image: "https://image.tmdb.org/t/p/w500/gPbM0MK8CP8A174rmUwGsADNYKD.jpg", progress: 20, category: "genres" },
  { id: 37, title: "Fast X", image: "https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg", progress: 30, category: "genres" },
  { id: 38, title: "Elemental", image: "https://image.tmdb.org/t/p/w500/6oH378KUfCEitzJkm07r97L0RsZ.jpg", progress: 0, category: "genres" },
  { id: 39, title: "Spider-Man: Across the Spider-Verse", image: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", progress: 90, category: "genres" },
  { id: 40, title: "Guardians of the Galaxy Vol. 3", image: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg", progress: 85, category: "genres" },

  // My List (41-50)
  { id: 41, title: "The Little Mermaid", image: "https://image.tmdb.org/t/p/w500/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg", progress: 25, category: "mylist" },
  { id: 42, title: "Ant-Man and the Wasp: Quantumania", image: "https://image.tmdb.org/t/p/w500/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg", progress: 15, category: "mylist" },
  { id: 43, title: "Creed III", image: "https://image.tmdb.org/t/p/w500/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg", progress: 60, category: "mylist" },
  { id: 44, title: "Shazam! Fury of the Gods", image: "https://image.tmdb.org/t/p/w500/A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg", progress: 0, category: "mylist" },
  { id: 45, title: "Avatar: The Way of Water", image: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg", progress: 0, category: "mylist" },
  { id: 46, title: "Black Panther: Wakanda Forever", image: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg", progress: 0, category: "mylist" },
  { id: 47, title: "Puss in Boots: The Last Wish", image: "https://image.tmdb.org/t/p/w500/kuf6dutpsT0vSVehic3EZIqkOBt.jpg", progress: 40, category: "mylist" },
  { id: 48, title: "Elvis", image: "https://image.tmdb.org/t/p/w500/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg", progress: 0, category: "mylist" },
  { id: 49, title: "Top Gun: Maverick", image: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg", progress: 30, category: "mylist" },
  { id: 50, title: "Jurassic World Dominion", image: "https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg", progress: 80, category: "mylist" },

  // Indonesian Movies (51-70)
  { id: 51, title: "Sewu Dino", image: "https://image.tmdb.org/t/p/w500/4Xkbpt8k9UIULRZq7m8W3x5V7vN.jpg", progress: 0, category: "indonesia" },
  { id: 52, title: "Petualangan Sherina 2", image: "https://image.tmdb.org/t/p/w500/7ZJqZ4J1W7Q6Q5Z6Q5Z6Q5Z6Q5Z.jpg", progress: 0, category: "indonesia" },
  { id: 53, title: "Agak Laen", image: "https://image.tmdb.org/t/p/w500/1Z6Q5Z6Q5Z6Q5Z6Q5Z6Q5Z6Q5Z6.jpg", progress: 0, category: "indonesia" },
  { id: 54, title: "Jin & Jun", image: "https://placehold.co/500x750?text=Jin+%26+Jun", progress: 0, category: "indonesia" },
  { id: 55, title: "Gadis Kretek", image: "https://placehold.co/500x750?text=Gadis+Kretek", progress: 0, category: "indonesia" },
  { id: 56, title: "Losmen Melati", image: "https://placehold.co/500x750?text=Losmen+Melati", progress: 0, category: "indonesia" },
  { id: 57, title: "Tira", image: "https://placehold.co/500x750?text=Tira", progress: 0, category: "indonesia" },
  { id: 58, title: "Dear Nathan: Thank You Salma", image: "https://placehold.co/500x750?text=Dear+Nathan", progress: 0, category: "indonesia" },
  { id: 59, title: "Setan Alas", image: "https://placehold.co/500x750?text=Setan+Alas", progress: 0, category: "indonesia" },
  { id: 60, title: "The Invisible Guest (Indonesia)", image: "https://placehold.co/500x750?text=The+Invisible+Guest", progress: 0, category: "indonesia" },
  { id: 61, title: "Sri Asih", image: "https://image.tmdb.org/t/p/w500/wL8dWrDW0KklUPZQz1UBZDwweTZ.jpg", progress: 0, category: "indonesia" },
  { id: 62, title: "Virgo and The Sparklings", image: "https://image.tmdb.org/t/p/w500/5Q5Z6Q5Z6Q5Z6Q5Z6Q5Z6Q5Z6Q5.jpg", progress: 0, category: "indonesia" },
  { id: 63, title: "Jailangkung 3", image: "https://placehold.co/500x750?text=Jailangkung+3", progress: 0, category: "indonesia" },
  { id: 64, title: "Kutukan Sembilan Setan", image: "https://placehold.co/500x750?text=Kutukan+Sembilan+Setan", progress: 0, category: "indonesia" },
  { id: 65, title: "Buya Hamka", image: "https://placehold.co/500x750?text=Buya+Hamka", progress: 0, category: "indonesia" },
  { id: 66, title: "Tali Mati", image: "https://placehold.co/500x750?text=Tali+Mati", progress: 0, category: "indonesia" },
  { id: 67, title: "Mangkujiwo 2", image: "https://placehold.co/500x750?text=Mangkujiwo+2", progress: 0, category: "indonesia" },
  { id: 68, title: "Generasi D'Bijis", image: "https://placehold.co/500x750?text=Generasi+D'Bijis", progress: 0, category: "indonesia" },
  { id: 69, title: "Jalan yang Jauh, Jangan Lupa Pulang", image: "https://placehold.co/500x750?text=Jalan+yang+Jauh", progress: 0, category: "indonesia" },
  { id: 70, title: "Gampang Cuan", image: "https://placehold.co/500x750?text=Gampang+Cuan", progress: 0, category: "indonesia" }
];